class AuditEvents:
    # Auth
    USER_LOGIN = "USER_LOGIN"
    USER_REGISTER = "USER_REGISTER"
    USER_LOGOUT = "USER_LOGOUT"
    LOGIN_FAILED = "LOGIN_FAILED"

    # Incident
    INCIDENT_REPORTED = "INCIDENT_REPORTED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_DELETED = "INCIDENT_DELETED"
    INCIDENT_MODIFIED = "INCIDENT_MODIFIED"

    # Review
    REVIEW_STARTED = "REVIEW_STARTED"
    REVIEW_COMPLETED = "REVIEW_COMPLETED"
    STATUS_CHANGED = "STATUS_CHANGED"
    REVIEW_MODIFIED = "REVIEW_MODIFIED"

    # Admin
    USER_VIEWED = "USER_VIEWED"
    AUDIT_LOG_VIEWED = "AUDIT_LOG_VIEWED"
    USER_MODIFIED = "USER_MODIFIED"

    # System
    RBAC_DENIED = "RBAC_DENIED"
    CONFIG_CHANGED = "CONFIG_CHANGED"
